language: python
sudo: required

python:
    - "2.7"

cache: pip

before_install:
  - lsb_release -a
  - sudo add-apt-repository ppa:deluge-team/develop -y
  - sudo apt-get update

# command to install dependencies
install:
  - bash -c "echo $APTPACKAGES"
  - sudo apt-get install $APTPACKAGES
  - pip install "tox==2.1.1"

env:
  global:
    - APTPACKAGES="python-libtorrent"
    - APTPACKAGES_GTKUI="python-gobject python-glade2"
    - DISPLAY=:99.0
  matrix:
    - TOX_ENV=pydef
    - TOX_ENV=flake8
#    - TOX_ENV=flake8-complexity
    - TOX_ENV=docs
#    - TOX_ENV=todo
    - TOX_ENV=trial              APTPACKAGES="$APTPACKAGES $APTPACKAGES_GTKUI"
    - TOX_ENV=pygtkui            APTPACKAGES="$APTPACKAGES $APTPACKAGES_GTKUI"
#    - TOX_ENV=testcoverage       APTPACKAGES="$APTPACKAGES $APTPACKAGES_GTKUI"
    - TOX_ENV=plugins

virtualenv:
  system_site_packages: true

# We use xvfb for the GTKUI tests
before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD
  - python -c "import libtorrent as lt; print lt.__version__"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - echo '2.0.0.dev0' > RELEASE-VERSION

script:
  - bash -c "echo $DISPLAY"
  - python setup.py build
  - sudo python setup.py install
  - tox -e $TOX_ENV
